import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./fonts";
import { Header } from "@/components/header";

import { ToDoStoreProvider } from "@/provider/todo-store-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen w-screen justify-center font-normal">
          <Header />
          <ToDoStoreProvider>{children}</ToDoStoreProvider>
        </main>
      </body>
    </html>
  );
}
